title: 
 en: A catalogue of Luigi Cherubini's educational and theoretical works (BacCh)
 de: Ein Verzeichnis der pädagogischen und theoretischen Werke Luigi Cherubinis (BacCh)
title_mobile: 
  en: Cherubini's educational works (BacCh)
  de: Cherubinis pädagogische Werke (BacCh)

email: info@rism.digital
baseurl: "/rism-catalogue-bacch"

sponsors:
  - url: https://fr.wikipedia.org/wiki/Licence_Creative_Commons
    logo: CC_license.png

languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["assets", "javascript", "rism-online-renderer", "images", "css", "README.md"]
parallel_localization: false
lang_from_path: false
sass:
  sourcemap: never

theme: rism-catalogue-theme

rism_catalogue: "publications/51004188"
